from abc import ABC, abstractmethod
from typing import List, Optional
from .models import Contact, ContactCreate, ContactUpdate

class IContactRepository(ABC):
    @abstractmethod
    def initialize(self) -> None: ...
    @abstractmethod
    def create(self, data: ContactCreate) -> Contact: ...
    @abstractmethod
    def get(self, id: str) -> Optional[Contact]: ...
    @abstractmethod
    def list(self, tag: Optional[str] = None) -> List[Contact]: ...
    @abstractmethod
    def update(self, id: str, data: ContactUpdate) -> Optional[Contact]: ...
    @abstractmethod
    def delete(self, id: str) -> bool: ...
    @abstractmethod
    def exists_email(self, email: str, exclude_id: Optional[str] = None) -> bool: ...
